name: mhtest
favicon: null
layout_spectrum: 0.5933950487524271
typography_spectrum: 0.1108604536857456
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.8207424392458051
  lightness: 0.40828197728842497
  saturation: 0.7186653784010559
  rhythmicContrast: 0.15965045406483114
purpose: []
